package com.example.iloveyou.ui.theme

object LoveQuoteProvider {
    private val loveQuotes = listOf(
        "You are my today and all of my tomorrows.",
        "I love you not only for what you are, but for what I am when I am with you.",
        "Love is composed of a single soul inhabiting two bodies.",
        "In all the world, there is no heart for me like yours. In all the world, there is no love for you like mine.",
        "Love is not about how much you say 'I love you,' but how much you prove that it's true.",
        "Love is a friendship set to music.",
        "The best thing to hold onto in life is each other.",
        "I love you because the entire universe conspired to help me find you.",
        "Love is not finding someone to live with; it's finding someone you can't live without.",
        "You are my today and all of my tomorrows.",
        "Love is not a noun to be defined, but a verb to be acted upon.",
        "To love is to receive a glimpse of heaven.",
        "I love you, not only for what you are but for what I am when I am with you.",
        "Love is the greatest refreshment in life.",
        "I have found the one whom my soul loves.",
        "Love is not what you say. Love is what you do.",
        "Love is when the other person's happiness is more important than your own.",
        "True love stories never have endings.",
        "The best and most beautiful things in the world cannot be seen or even touched. They must be felt with the heart.",
        "Love is a canvas furnished by nature and embroidered by imagination.",
        "Love is like a flower; it grows and blossoms with care and affection.",
        "I need you like a heart needs a beat.",
        "I am forever grateful for the happiness and joy you have brought into my life.",
        "You're the love of my life and my best friend. I'm so happy that I get to spend the rest of my life with you.",
        "Let's make this lovely journey last for a lifetime, do not ever let me go.",
        "You are the sun in my day, the wind in my sky, the waves in my ocean, and the beat in my heart.",
        "Every time you smile at someone, it is an action of love, a gift to that person, a beautiful thing.",
        "You are my life, my inspiration, my strength and my soulmate. I love you so much.",
        "I love you because I know no matter what happens, you'll always love me back.",
        "You are my today and all of my tomorrows.",
        "I love you not only for what you are, but for what I am when I am with you.",
        "Love is composed of a single soul inhabiting two bodies.",
        "In all the world, there is no heart for me like yours. In all the world, there is no love for you like mine.",
        "Love is not about how much you say 'I love you,' but how much you prove that it's true.",
        "Love is a friendship set to music.",
        "The best thing to hold onto in life is each other.",
        "I love you because the entire universe conspired to help me find you.",
        "Love is not finding someone to live with; it's finding someone you can't live without.",
        "You are my today and all of my tomorrows.",
        "Love is not a noun to be defined, but a verb to be acted upon.",
        "To love is to receive a glimpse of heaven.",
        "I love you, not only for what you are but for what I am when I am with you.",
        "Love is the greatest refreshment in life.",
        "I have found the one whom my soul loves.",
        "Love is not what you say. Love is what you do.",
        "Love is when the other person's happiness is more important than your own.",
        "True love stories never have endings.",
        "The best and most beautiful things in the world cannot be seen or even touched. They must be felt with the heart.",
        "Love is a canvas furnished by nature and embroidered by imagination.",
        "Love is like a flower; it grows and blossoms with care and affection.",
        "I need you like a heart needs a beat.",
        "I am forever grateful for the happiness and joy you have brought into my life.",
        "You're the love of my life and my best friend. I'm so happy that I get to spend the rest of my life with you.",
        "Let's make this lovely journey last for a lifetime, do not ever let me go.",
        "You are the sun in my day, the wind in my sky, the waves in my ocean, and the beat in my heart.",
        "Every time you smile at someone, it is an action of love, a gift to that person, a beautiful thing.",
        "You are my life, my inspiration, my strength and my soulmate. I love you so much.",
        "I love you because I know no matter what happens, you'll always love me back.",
        "You are my today and all of my tomorrows.",
        "I love you not only for what you are, but for what I am when I am with you.",
        "Love is composed of a single soul inhabiting two bodies.",
        "In all the world, there is no heart for me like yours. In all the world, there is no love for you like mine.",
        "Love is not about how much you say 'I love you,' but how much you prove that it's true.",
        "Love is a friendship set to music.",
        "The best thing to hold onto in life is each other.",
        "I love you because the entire universe conspired to help me find you.",
        "Love is not finding someone to live with; it's finding someone you can't live without.",
        "You are my today and all of my tomorrows.",
        "Love is not a noun to be defined, but a verb to be acted upon.",
        "To love is to receive a glimpse of heaven.",
        "I love you, not only for what you are but for what I am when I am with you.",
        "Love is the greatest refreshment in life.",
        "I have found the one whom my soul loves.",
        "Love is not what you say. Love is what you do.",
        "Love is when the other person's happiness is more important than your own.",
        "True love stories never have endings.",
        "The best and most beautiful things in the world cannot be seen or even touched. They must be felt with the heart.",
        "Love is a canvas furnished by nature and embroidered by imagination.",
        "Love is like a flower; it grows and blossoms with care and affection.",
        "I need you like a heart needs a beat.",
        "I am forever grateful for the happiness and joy you have brought into my life.",
        "You're the love of my life and my best friend. I'm so happy that I get to spend the rest of my life with you.",
        )

    fun getRandomQuotes(): String{
        return loveQuotes.random()
    }

    fun getQuotes(): List<String> = loveQuotes
}